### ISSUE TITLE
ConnectionNotFoundError: Connection "default" was not found.

### ISSUE THREAD

**Issue by i-CNNN** [hackycy/sf-midway-admin#1]
## Bug report 启动服务报错：
ConnectionNotFoundError: Connection "default" was not found.

#### Steps to reproduce（问题复现步骤）
1. 把docs/example下的配置文件复制到src/config下，修改redis、mysql配置后启动服务，报错如下图中的数据库配置，及错误

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/24954758/112617676-3a3ccd80-8e60-11eb-99f8-09b23f933ba4.png)
![image](https://user-images.githubusercontent.com/24954758/112623157-f13c4780-8e66-11eb-9141-83f53c465506.png)

**Comment by hackycy** [comment]
@i-CNNN 把`config.typeorm`改成`config.orm`即可。

**Comment by hackycy** [comment]
改成一下配置
``` javascript
config.orm = {
      type: 'mysql',
      host: '127.0.0.1',
      port: 3306,
      username: 'root',
      password: '123456',
      database: 'sf-admin',
      synchronize: false,
      logging: true,
      supportBigNumbers: false,
}
```
目前example中的实例还没改过来，和egg版配置不一样哈。

**Comment by i-CNNN** [comment]
> 改成一下配置
> 
> ```js
> config.orm = {
>       type: 'mysql',
>       host: '127.0.0.1',
>       port: 3306,
>       username: 'root',
>       password: '123456',
>       database: 'sf-admin',
>       synchronize: false,
>       logging: true,
>       supportBigNumbers: false,
> }
> ```
> 
> 目前example中的实例还没改过来，和egg版配置不一样哈。

**Comment by i-CNNN** [comment]
谢谢大佬
