### ISSUE TITLE
您好，导入数据库脚本后 默认登录用户名密码是多少

### ISSUE THREAD

**Issue by dgo2dance** [hackycy/sf-midway-admin#13]
您好，导入数据库脚本后 默认登录用户名密码是多少   可以加微信交流嘛

**Comment by hackycy** [comment]
@willnode1024  之前文档有写可能被我忽略删掉了，默认密码都是`123456`，超级管理员是`rootadmin`

**Comment by hackycy** [comment]
@willnode1024 文档有写的哈：https://blog.si-yee.com/sf-admin-cli/midway/#演示地址

**Comment by hackycy** [comment]
@willnode1024 你有需要就加把，我微信号是yzy894178522
