### ISSUE TITLE
您好，用sfadmin命令 初始化的项目 不是多页签的   就是这样的吗    有没有多页签的

### ISSUE THREAD

**Issue by dgo2dance** [hackycy/sf-midway-admin#15]
## Feature request（新功能建议）
您好，用sfadmin命令 初始化的项目 不是多页签的   就是这样的吗    有没有多页签的

**Comment by hackycy** [comment]
@willnode1024 midway我挺久没有更新了，后续计划是没有什么大bug是不会更新了，nest版本会一直进行维护和更新新功能。所以前端的东西你可以参考nest版本的抄过去。
