### ISSUE TITLE
工程里的分支v3版本的一些疑问

### ISSUE THREAD

**Issue by wwb568109135** [hackycy/sf-midway-admin#17]
## Feature request（新功能建议）

【1】工程里的分支v3版本是sf-midway-admin的midway3.0版本吗？
【2】工程里的分支v3版本是sf-midway-admin的midway2.0版本升到midway3.0的版本吗？

**Comment by hackycy** [comment]
v3只是打算支持midway v3，但未开始编码测试

**Comment by wwb568109135** [comment]
> 

等大佬支持后再跟进！
看了一下项目的整体工程，设计合理和清晰，很不错的工程，已经star和fork了

辛苦啦
