### ISSUE TITLE
Redis能否去掉

### ISSUE THREAD

**Issue by robinma** [hackycy/sf-midway-admin#7]
## Feature request（新功能建议）

Redis对于个人用户，想使用云函数，这个组件成本太高了，能否有无redis版本

**Comment by hackycy** [comment]
找到使用该函数的地方，根据相关Api的定义重写。大多数都是登陆相关的

https://github.com/hackycy/sf-midway-admin/blob/fa75ed55d7d484f3a7c80b509c2d25648cd764a3/src/service/base.ts#L13

如果用不了Redis，定时任务、在线用户这两个模块是没办法使用的。

> 阿里云的Redis低配置一年很便宜。
