### ISSUE TITLE
前台登陆获取验证码时显示“登录无效或无权限访问”

### ISSUE THREAD

**Issue by alialiya** [hackycy/sf-midway-admin#8]
## Bug report（问题描述）
本地代码预览，运行后端DEV正常无报错，运行前端DEV正常无报错
#### Screenshot or Gif（截图或动态图）
运行后端DEV截图
![image](https://user-images.githubusercontent.com/17696202/125914163-5e446c16-76a2-4e6a-ab91-d936a2790d5b.png)
运行前端DEV截图
![image](https://user-images.githubusercontent.com/17696202/125914195-99f53625-e31b-47b4-8bc8-24195fe722b9.png)
前端登陆截图
![image](https://user-images.githubusercontent.com/17696202/125914305-9c424557-8c75-4c9e-b8e5-8ae1042ea48f.png)

#### Other relevant information（格外信息）
- Your OS: Windows10
- Node.js version: v12.18.3
- Mysql version: 10.4.13-MariaDB
- Redis version: Redis-x64-3.0.504

**Comment by hackycy** [comment]
@alialiya Midway版的前端用midway分支，不要用dev分支哈。dev分支只支持[Nest版本](https://github.com/hackycy/sf-nest-admin)

**Comment by hackycy** [comment]
没问题我关掉了哈
