### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by chenxin9482** [hackycy/sf-midway-admin#9]
#### Steps to reproduce（问题复现步骤）

按照readme的步骤走的，好像是bull的问题
1. 新建数据库并导入数据库脚本
2. 修改数据库配置信息
3. npm i
4. npm run dev
#### Screenshot or Gif（截图或动态图）
![1627643564(1)](https://user-images.githubusercontent.com/65519955/127645053-f1271720-f6df-436f-9e5b-28788650f2dd.jpg)

#### Other relevant information（格外信息）
- Your OS: windows 10
- Node.js version:14.16.0
- Mysql version: 8.0.26
- Redis version:5.0.10

**Comment by hackycy** [comment]
@chenxin9482 看一下你的配置文件

**Comment by baolisboa** [comment]
> ## Bug report（问题描述）
> #### Steps to reproduce（问题复现步骤）
> 按照readme的步骤走的，好像是bull的问题
> 
> 1. 新建数据库并导入数据库脚本
> 2. 修改数据库配置信息
> 3. npm i
> 4. npm run dev
> 
> #### Screenshot or Gif（截图或动态图）
> ![1627643564(1)](https://user-images.githubusercontent.com/65519955/127645053-f1271720-f6df-436f-9e5b-28788650f2dd.jpg)
> 
> #### Other relevant information（格外信息）
> * Your OS: windows 10
> * Node.js version:14.16.0
> * Mysql version: 8.0.26
> * Redis version:5.0.10

解决了吗？我也是这个问题    TypeError: Cannot read property 'default' of undefined

**Comment by hackycy** [comment]
@baolisboa 我无法进行复现，请提供一下你的配置

**Comment by chenxin9482** [comment]
config/config.default.ts 是这样的：
![1627780194(1)](https://user-images.githubusercontent.com/65519955/127756020-bc5e2adb-9e49-4544-aeee-d7708cbf0a30.jpg)

**Comment by chenxin9482** [comment]
除了数据库都是默认的配置

**Comment by hackycy** [comment]
@chenxin9482 redis、orm、bull的配置在哪里

**Comment by hackycy** [comment]
@chenxin9482 `config.prod.ts`的配置只有在生产环境生效，运行`npm run dev`读取的配置是读取的`config.local.ts`

**Comment by hackycy** [comment]
@baolisboa @chenxin9482 把 [sample](https://github.com/hackycy/sf-midway-admin/tree/dev/docs/sample) 下的 `config.local.ts`拷贝到`src/config`目录再进行修改配置
